version: "3.8"
services:
    postgres:
        image: postgres:latest
        restart: always
        environment: 
          - POSTGRES_USER=${POSTGRES_USER:-postgres}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
          - POSTGRES_DB=${POSTGRES_DB:-vaccinations}
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - 5432:5432
        volumes:
          - ./data/resources/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
          - ./data/resources/sql/populate_tables.sql:/docker-entrypoint-initdb.d/populate_tables.sql
    backend:
        build: ./backend
        restart: always
        environment: 
          - POSTGRES_USER=${POSTGRES_USER:-postgres}
          - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
          - POSTGRES_URL=${POSTGRES_URL:-postgres:5432}
          - POSTGRES_DB=${POSTGRES_DB:-vaccinations}
        ports:
          - 8080:8080
        volumes:
        - ./backend:/app
        depends_on:
          - "postgres"
        command: bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done; python main.py'
    frontend:
        build: ./frontend
        restart: always
        ports: 
          - 3000:3000
        volumes:
          - ./frontend:/app